from django.urls import path
from . import views
from django.contrib import admin


urlpatterns = [
    # path("", views.index, name="TokenObtainPairView"),
    path('admin/', admin.site.urls),
    path('me/', views.me_view,
         name='me_view'),
    path('oauth2/google/login/', views.google_login_view,
         name='google_oauth2_login'),
    path('oauth2/google/callback/', views.google_callback_view,
         name='google_oauth2_login'),
    path('oauth2/vk/login/', views.vk_login_view, name='vk_oauth2_login'),
    path('oauth2/vk/callback/',
         views.vk_callback_view, name='vk_oauth2_callback'),
    path('oauth2/steam/login/', views.steam_login_view, name='vk_oauth2_login'),
    path('oauth2/steam/callback/',
         views.steam_callback_view, name='vk_oauth2_callback'),
    path('cases/get_case_content/<str:case_id>/',
         views.get_case_content_view, name='get_case_content'),
    path('cases/open_case/<str:case_id>/',
         views.get_open_case_view, name='get_open_case_view'),
    path('cases/<str:case_type>/',
         views.get_cases_by_type_view, name='get_cases_by_type_view'),
    path('advertisement/',
         views.advertisement_view, name='advertisement_view'),
    path('csrf/',
         views.get_csrf_view, name='get_csrf_view'),
    path('main-page-background/',
         views.get_main_page_background_view, name='get_main_page_background_view'),
    path('raffles/take-a-part/',
         views.raffles_take_a_part_view, name='raffles_take_a_part_view'),
    path('raffles/',
         views.raffles_list_view, name='raffles_list_view'),
    path('get-inventory-items/',
         views.get_inventory_items_view, name='get_inventory_items_view'),
    path('get-server-inventory-items/',
         views.get_inventory_server_items_view, name='get_inventory_server_items_view'),
    path('upgrade-item/',
         views.upgrade_item_view, name='upgrade_item_view'),
    path('make-contract/',
         views.make_contract_view, name='make_contract_view'),
    path('create-battles/',
         views.create_battles_view, name='create_battles_view'),
    path('global-battle-info/',
         views.global_battles_info_view, name='global_battles_info_view'),
    path('active-battle-info/',
         views.active_battles_info_view, name='active_battles_info_view'),
    path('battles/game/<str:battle_id>/',
         views.get_battle_info_view, name='get_battle_info_view'),
    path('profile-info/',
         views.profile_info_view, name='profile_info_view'),
    path('set-trade-link/',
         views.set_trade_link_view, name='set_trade_link_view'),
    path('sell-inventory-item/',
         views.sell_inventory_item_view, name='sell_inventory_item_view'),
]
