# Generated by Django 5.2.5 on 2025-10-27 07:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamitemcs',
            name='chance_battle_scarred',
            field=models.DecimalField(blank=True, decimal_places=10, default=Decimal('65.0000000000'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='steamitemcs',
            name='chance_field_tested',
            field=models.DecimalField(blank=True, decimal_places=10, default=Decimal('9.0000000000'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='steamitemcs',
            name='chance_well_worn',
            field=models.DecimalField(blank=True, decimal_places=10, default=Decimal('25.0000000000'), max_digits=20),
        ),
    ]
