# Generated by Django 5.2.5 on 2025-09-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steamitemcs',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='steamitemcs',
            name='name_ru',
        ),
        migrations.AddField(
            model_name='steamitemcs',
            name='item_model',
            field=models.CharField(default='123', max_length=50),
        ),
        migrations.AddField(
            model_name='steamitemcs',
            name='item_style',
            field=models.CharField(default='123', max_length=50),
        ),
        migrations.AlterField(
            model_name='steamitemcs',
            name='name',
            field=models.CharField(default='123', max_length=70),
        ),
    ]
