# Generated by Django 5.2.5 on 2025-09-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamitemcs',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
