# Generated by Django 5.2.5 on 2025-09-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_steamitemcs_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamitemcs',
            name='item_model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='steamitemcs',
            name='item_style',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='steamitemcs',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
