# Generated by Django 5.2.5 on 2025-10-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_steamitemcs_chance_battle_scarred_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
