# Generated by Django 5.2.5 on 2025-09-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_steamitemcs_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCoefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raffles_global', models.FloatField(default=1.0)),
                ('cases_global', models.FloatField(default=1.0)),
                ('upgrades_global', models.FloatField(default=1.0)),
                ('contracts_global', models.FloatField(default=1.0)),
                ('battles_global', models.FloatField(default=1.0)),
            ],
            options={
                'verbose_name': 'Глобальный коэффициент',
                'verbose_name_plural': 'Глобальный коэффициент',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='battles_chance',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='case_chance',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='contracts_chance',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='upgrade_chance',
            field=models.FloatField(default=1),
        ),
    ]
