# Generated by Django 5.2.5 on 2025-10-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_case_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffles',
            name='exterior_wear',
            field=models.CharField(choices=[('factory_new', 'Factory New'), ('minimal_wear', 'Minimal Wear'), ('field_tested', 'Field-Tested'), ('well_worn', 'Well-Worn'), ('battle_scarred', 'Battle-Scarred')], default='field_tested', max_length=20),
        ),
    ]
