# Generated by Django 5.2.5 on 2025-09-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_steamitemcs_item_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='steamitemcs',
            name='name',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
