# Generated by Django 5.2.5 on 2025-09-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_globalcoefficient_user_battles_chance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalcoefficient',
            options={'verbose_name': 'Глобальные коэффициенты', 'verbose_name_plural': 'Глобальные коэффициенты'},
        ),
        migrations.AlterField(
            model_name='globalcoefficient',
            name='battles_global',
            field=models.FloatField(default=1.0, verbose_name='Коэф. баттлов'),
        ),
        migrations.AlterField(
            model_name='globalcoefficient',
            name='cases_global',
            field=models.FloatField(default=1.0, verbose_name='Коэф. кейсов'),
        ),
        migrations.AlterField(
            model_name='globalcoefficient',
            name='contracts_global',
            field=models.FloatField(default=1.0, verbose_name='Коэф. контрактов'),
        ),
        migrations.AlterField(
            model_name='globalcoefficient',
            name='raffles_global',
            field=models.FloatField(default=1.0, verbose_name='Коэф. розыгрышей'),
        ),
        migrations.AlterField(
            model_name='globalcoefficient',
            name='upgrades_global',
            field=models.FloatField(default=1.0, verbose_name='Коэф. апгрейдов'),
        ),
    ]
