# Generated by Django 5.2.5 on 2025-10-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_raffles_exterior_wear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalcoefficient',
            name='battles_global',
        ),
        migrations.RemoveField(
            model_name='globalcoefficient',
            name='raffles_global',
        ),
    ]
