# Generated by Django 5.2.5 on 2025-09-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_case_name_alter_steamitemcs_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='type',
            field=models.CharField(choices=[('standart_case', 'Стандартный кейс'), ('season_case', 'Сезонный кейс'), ('bloger_case', 'Блогерский кейс')], default='standart_case', max_length=20),
        ),
    ]
