# Generated by Django 5.2.5 on 2025-09-28 11:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_globalcoefficient_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('players_amount', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_battles', to='main_app.user')),
                ('players', models.ManyToManyField(blank=True, related_name='battles', to='main_app.user')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_battles', to='main_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='BattleDrop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drops', to='main_app.battle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_drops', to='main_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='BattleDropItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('round', models.PositiveSmallIntegerField()),
                ('battle_drop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main_app.battledrop')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='BattleCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_amount', models.PositiveSmallIntegerField()),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_battles', to='main_app.battle')),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_cases', to='main_app.case')),
            ],
            options={
                'unique_together': {('battle', 'case')},
            },
        ),
    ]
