# Generated by Django 5.2.5 on 2025-09-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_case_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='money_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
