# Generated by Django 5.2.5 on 2025-10-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_battle_battledrop_battledropitem_battlecase'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='game_state',
            field=models.CharField(choices=[('waiting', 'Ожидание'), ('in_process', 'В процессе'), ('canceled', 'Отменен'), ('finished', 'Завершен успешно'), ('failed', 'Не состоялся')], default='waiting', max_length=20),
        ),
    ]
