# Generated by Django 5.2.5 on 2025-10-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_globalcoefficient_battles_global_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='created_game',
            field=models.CharField(blank=True, choices=[('upgrade', 'Upgrade'), ('roulette', 'Roulette'), ('case', 'Case'), ('battle', 'Battle'), ('contract', 'Contract')], default='upgrade', max_length=20, null=True),
        ),
    ]
