# Generated by Django 5.2.5 on 2025-09-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_user_money_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
