# Generated by Django 5.2.5 on 2025-10-03 13:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_battle_game_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlecase',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
