# Generated by Django 5.2.5 on 2025-10-03 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_battlecase_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battlecase',
            name='created_at',
        ),
    ]
