# Generated by Django 5.2.5 on 2025-09-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_case_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
