# Generated by Django 5.2.5 on 2025-09-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_case_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roulet_chance',
            field=models.FloatField(default=1),
        ),
    ]
