# Generated by Django 5.2.5 on 2025-10-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_battlecase_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battlecase',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='battlecase',
            name='position',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
