# Generated by Django 5.2.5 on 2025-10-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_battlecase_options_battlecase_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='best_case',
            field=models.JSONField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='best_skin',
            field=models.JSONField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='total_battles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_case_opened',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_contracts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_upgrades',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
