# Generated by Django 5.2.5 on 2025-09-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_user_roulet_chance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='item_state_chance',
            field=models.FloatField(default=1),
        ),
    ]
