# Generated by Django 5.2.5 on 2025-09-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_user_item_state_chance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=255)),
                ('subTitle_1', models.CharField(max_length=255)),
                ('imgUrl_1', models.CharField(max_length=255)),
                ('timer_1', models.PositiveIntegerField()),
                ('title_2', models.CharField(max_length=255)),
                ('subTitle_2', models.CharField(max_length=255)),
                ('imgUrl_2', models.CharField(max_length=255)),
            ],
        ),
    ]
