# Generated by Django 5.2.5 on 2025-09-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='subTitle_1_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='subTitle_1_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='subTitle_2_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='subTitle_2_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='title_1_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='title_1_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='title_2_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='title_2_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='subTitle_1',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='subTitle_2',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title_1',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title_2',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
