# Generated by Django 5.2.5 on 2025-10-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_user_best_case_alter_user_best_skin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='best_case',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='best_skin',
            field=models.JSONField(default=dict),
        ),
    ]
