# Generated by Django 5.2.5 on 2025-09-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_advertisement_subtitle_1_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='subTitle_1_en',
            field=models.CharField(default='daw', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='subTitle_1_ru',
            field=models.CharField(default='12', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='subTitle_2_en',
            field=models.CharField(default='12', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='subTitle_2_ru',
            field=models.CharField(default='12', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title_1_en',
            field=models.CharField(default='123', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title_1_ru',
            field=models.CharField(default='123', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title_2_en',
            field=models.CharField(default='123', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title_2_ru',
            field=models.CharField(default='123', max_length=255),
            preserve_default=False,
        ),
    ]
