# Generated by Django 5.2.5 on 2025-10-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_user_best_case_alter_user_best_skin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_raffles',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
