# Generated by Django 5.2.5 on 2025-10-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_user_total_raffles'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalStateCoeff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_new', models.FloatField(default=0, verbose_name='Factory New')),
                ('minimal_wear', models.FloatField(default=0, verbose_name='Minimal Wear')),
                ('field_tested', models.FloatField(default=0, verbose_name='Field-Tested')),
                ('well_worn', models.FloatField(default=0, verbose_name='Well-Worn')),
                ('battle_scarred', models.FloatField(default=0, verbose_name='Battle-Scarred')),
            ],
            options={
                'verbose_name': 'Глобальные коэффициенты состояния',
                'verbose_name_plural': 'Глобальные коэффициенты состояния',
            },
        ),
    ]
