# Generated by Django 5.2.5 on 2025-09-14 14:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_advertisement_subtitle_1_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='timer_1',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='data_and_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
