# Generated by Django 5.2.5 on 2025-10-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_globalstatecoeff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trade_link',
            field=models.URLField(default='', null=True),
        ),
    ]
