# Generated by Django 5.2.5 on 2025-09-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_remove_advertisement_timer_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='imgUrl_1',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='imgUrl_2',
            field=models.URLField(max_length=255),
        ),
    ]
