# Generated by Django 5.2.5 on 2025-09-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_advertisement_imgurl_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundMainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_background_url', models.URLField()),
                ('mobile_background_url', models.URLField()),
            ],
        ),
    ]
