# Generated by Django 5.2.5 on 2025-10-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_user_trade_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='best_case',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='best_skin',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='trade_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
