# Generated by Django 5.2.5 on 2025-10-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_user_best_case_alter_user_best_skin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-created_at'], 'verbose_name': 'Case', 'verbose_name_plural': 'Cases'},
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_reason',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
