# Generated by Django 5.2.5 on 2025-09-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_backgroundmainpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundmainpage',
            name='mobile_background_grass_url',
            field=models.URLField(default='http://localhost:3000/123'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backgroundmainpage',
            name='pc_background_grass_url',
            field=models.URLField(default='http://localhost:3000/123'),
            preserve_default=False,
        ),
    ]
