# Generated by Django 5.2.5 on 2025-10-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_case_options_user_blocked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamitemcs',
            name='price_battle_scarred',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AddField(
            model_name='steamitemcs',
            name='price_factory_new',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AddField(
            model_name='steamitemcs',
            name='price_field_tested',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AddField(
            model_name='steamitemcs',
            name='price_minimal_wear',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AddField(
            model_name='steamitemcs',
            name='price_well_worn',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=10),
        ),
    ]
