# Generated by Django 5.2.5 on 2025-10-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_steamitemcs_price_battle_scarred_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalActionAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_upgrades', models.PositiveIntegerField(default=0, verbose_name='Суммарно апгрейдов')),
                ('total_opened_cases', models.PositiveIntegerField(default=0, verbose_name='Суммарно откртых кейсов')),
                ('total_contracts', models.PositiveIntegerField(default=0, verbose_name='Суммарно контрактов')),
            ],
            options={
                'verbose_name': 'Общее количество действий на сайте',
                'verbose_name_plural': 'Общее количество действий на сайте',
            },
        ),
    ]
