# Generated by Django 5.2.5 on 2025-10-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_totalactionamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='case_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
