# Generated by Django 5.2.5 on 2025-10-21 13:00

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_inventoryitem_case_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrownFilterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', multiselectfield.db.fields.MultiSelectField(choices=[('usuall', 'Usual'), ('rare', 'Rare'), ('elite', 'Elite'), ('epic', 'Epic'), ('classified', 'Classified')], default=['elite', 'epic'], max_length=100)),
                ('exterior_wear', multiselectfield.db.fields.MultiSelectField(choices=[('factory_new', 'Factory New'), ('minimal_wear', 'Minimal Wear'), ('field_tested', 'Field-Tested'), ('well_worn', 'Well-Worn'), ('battle_scarred', 'Battle-Scarred')], default=['factory_new', 'minimal_wear', 'field_tested', 'well_worn', 'battle_scarred'], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
