# Generated by Django 5.2.5 on 2025-10-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_crownfilterdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crownfilterdata',
            options={'verbose_name': 'Фильтр Crown', 'verbose_name_plural': 'Фильтр Crown'},
        ),
        migrations.AlterField(
            model_name='crownfilterdata',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
