# Generated by Django 5.2.5 on 2025-10-25 19:01

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_alter_crownfilterdata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crownfilterdata',
            name='rarity',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('usuall', 'Usual'), ('rare', 'Rare'), ('classified', 'Classified'), ('elite', 'Elite'), ('epic', 'Epic')], default=['elite', 'epic'], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, default='/images/avatar.svg', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='username', max_length=200, unique=True),
        ),
    ]
